dist: trusty

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

sudo: false

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
