language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

matrix:
    fast_finish: true

install:
    - composer install

script:
    - phpunit --version
    - phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
